### ISSUE TITLE
What to do with the output?

### ISSUE THREAD

**Issue by fstanis** [erikdesjardins/interpolate-loader#10]
I'm a bit confused what to do with the output, e.g.

```js
module.exports = {
  entry: 'file-loader?name=[name].[ext]!extricate-loader!interpolate-loader!./manifest.json',
  {
    filename: 'out.js'
  },
  ...
```

out.js has no useful output, just the line `module.exports = __webpack_require__.p + "manifest.json";` (plus the normal webpack boilerplate).

I currently solve it using ExtractTextPlugin, which just feels clunky:
```js
module.exports = {
  output: {
    filename: 'manifest.json',
    path: DIST_DIR,
  },
  entry: './manifest.json',
  modules: {
    rules: [
      ...
      {
        test: /manifest\.json$/,
        use: ExtractTextPlugin.extract([
          'raw-loader',
          'extricate-loader',
          'interpolate-loader'
        ])
      }
   },
  plugins: {
    ...
    new ExtractTextPlugin('manifest.json')
  }
}
```

**Comment by erikdesjardins** [comment]
Oh, yeah, the readme is wrong!

Unfortunately, Webpack doesn't let you use non-js files as an entry point, so you have to work around that, like your example. I wrote a plugin for this ([inert-entry-webpack-plugin](https://github.com/erikdesjardins/inert-entry-webpack-plugin)), which makes it a bit nicer.

e.g. you could do

```js
module.exports = {
  output: {
    filename: 'manifest.json',
    path: DIST_DIR,
  },
  entry: 'extricate-loader!interpolate-loader!./manifest.json',
  plugins: {
    ...
    new InertEntryPlugin()
  }
}
```

I'll fix the readme.
